name: s_trading
description: A Flutter project for S-TRADING Madagascar
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  fluttertoast: ^8.2.2
  flutter_barcode_scanner: ^2.0.0
  font_awesome_flutter: ^10.4.0
  barcode_widget: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
   - assets/logo_strading.jpg
   - assets/avatar.jpg


